### PR TITLE
Revert the changes for new build schema

### PR DESCRIPTION
**Pull request by nicodh**
Since these changes somehow introduce errors on Mac, not being able to connect over SSL anymore, we have to revert them...

### CODE REVIEW

**Comment by flub** [comment]
Did you try to install libetpan from their current master branch?

**Comment by nicodh** [comment]
No not yet - how could it help if we had to rely on a self compiled libetpan as dependency?
I thought you were aiming to have less libraries shipped and make use of existing ones?

**Comment by ralphtheninja** [comment]
If we can make mac work against a system installed `libdeltachat.so` from `dc-core-rust`, then we shouldn't revert these changes.

**Comment by nicodh** [comment]
I would say then we should reapply the changes, but as long as we don't have a solution it should not be in master. But maybe I miss something - what are the advantages to have these changes in master even if it breaks the SSL communication on mac?

**Comment by nicodh** [comment]
So I compiled current master of libetpan - but how do I configure binding.gyp to link it to that compiled version?

**Comment by nicodh** [comment]
So I updated pkgconfig/libetpan.pc to the new prefix  - so I guess it would use that one now, but it didn't change anything. Still get error #43 when  trying to connect...

**Comment by ralphtheninja** [comment]
On mac you use otool I think. @Jikstra ?

**Comment by flub** [comment]
There's a complicating issue that libetpan switched to using pkg-config on their master branch but the last release (and how dc-core supports libetpan) uses the libetpan-config binary.  You can see this beautifully here too: https://travis-ci.org/deltachat/deltachat-node/jobs/529977950  The world is just conspiring against me.

Anyway, if you set CFLAGS="-I/usr/local/include" and LDFLAGS="-L/usr/lib/ -llibetpan" and comment out all the etpan references in dc-core/meson.build (line 77-108) and replace it with a single `etpan = dependency('', required: False)` line.  That may work.  I'm still trying to figure out what the best approach is for in the repo, or indeed whether to just wait till rust works and etpan is gone because something nice is basically wasted now I guess?

**Comment by nicodh** [comment]
> Anyway, if you set CFLAGS="-I/usr/local/include" and LDFLAGS="-L/usr/lib/ -llibetpan" 

Do you mean as environment variable?
My local path to self compiled libetpan is /sw/lib/
Should I add that instead of /usr/lib/ here?

**Comment by flub** [comment]
1. yes, environment variable - sorry
2. yes, replace /usr/lib with /sw/lib/ in my instructios if that was the prefix you used to install etpan

**Comment by flub** [comment]
Also two more things: I think I may have found a way to do this simpler in dc-core which isn't too much work.  I'll try that out.

And secondly if we do want to revert this is reverting too much, e.g. it goes back to node 8 etc.  If we do need to revert let's only revert osx support.  But than again maybe it's better to evolve to evolve straight to dcc-rs instead.  Although I think it makes more sense to try and do a dc-core based desktop release first.

**Comment by nicodh** [comment]
We could say reverting is obsolete, since the SSL connecting issue on Mac is gone with rust-core (although there are a lot of other issues now).
It's a bit a strategic question: do we strive to always have a working master or do we say master is always "bleeding edge" and only releases have to be stable & working...

Btw: did you see my message in deltachat desktop group? I asked you there about revering before this PR, but you never responded. Did you get my invitation?

**Comment by nicodh** [comment]
I also posted there that travis.yml, README & docker stuff has to be checked by someone else since I was not sure what to revert and what not....

**Comment by flub** [comment]
huh, i'm not in the desktop group chat nor saw your invitation... my dc address is flub@testrun.org btw.

**Comment by flub** [comment]
@nicodh tested this on ci now and this all won't fix your issue

**Comment by Jikstra** [comment]
As mac seems to work again, i think we can close this? @nicodh

**Pull request closed without merging**
