### PR TITLE
Put napi macros in own header file

### PR DESCRIPTION
**Pull request by Jikstra**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Nice!

**Comment by r10s** [comment]
currently, the "system" `napi-macros.h` has the same name as "deltas"  `napi-macros.h`, the correct file is only selected by the search path precedence. was this the intent in some way?

otherwise i would suggest to  avoid confusions by using eg. `napi-macros-extensions.h` instead of "deltas"  `napi-macros.h`. (confusions might be eg. the "delta" `napi-macros.h` may not be included when it is missing for some reason - instead the "system" `napi-macros.h` is used without a "header not found error". another case i can imagine is that the delta dir is added by the build system to the system paths, the `#include <napi-macros.h>` in the "delta" `napi-macros.h`)

**Comment by ralphtheninja** [comment]
> otherwise i would suggest to avoid confusions by using eg. napi-macros-extensions.h instead of "deltas" napi-macros.h

:+1:

**Comment by r10s** [comment]
i do a pr

**Pull request merged**
