### PR TITLE
[wip] Remove polling

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/deltachat/deltachat-node/issues/226, closes https://github.com/deltachat/deltachat-node/issues/79

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I tried desktop locally but it crashes after a while. No idea why.

**Comment by Jikstra** [comment]
> I tried desktop locally but it crashes after a while. No idea why.

Any ideas how to proceed? Would be quite nice to get rid of that hack.

**Comment by ralphtheninja** [comment]
> Any ideas how to proceed? Would be quite nice to get rid of that hack.

We need to solve the crash. It's something related to mutexes.

**Comment by ralphtheninja** [comment]
@flub Is this still relevant now?

**Comment by nicodh** [comment]
I tested this branch (after rebasing it on current master)
It runs until a new message is coming in, then it crashes with:
`Receiving message INBOX/180...`
`dyld: lazy symbol binding failed: Symbol not found: _pgp_memory_new`
  `Referenced from: /Users/ndh/Documents/projekte/deltachat/deltachat-desktop/node_modules/deltachat-node/build/Release/deltachat.node`
  `Expected in: flat namespace
`

**Comment by nicodh** [comment]
So I found this happened since the -Drpgp=true meson argument was missing (got lost when rebasing).
After adding it I could run the nodes module from command line without crashing.
But running it from deltachat-desktop (master) resulted in a crash:

> Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00000001042c9d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8c51d457 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff8c395420 abort + 129
3   com.github.Electron.framework 	0x000000010953da84 uv_mutex_lock + 20
4   com.github.Electron.framework 	0x0000000109439a49 napi_call_threadsafe_function + 41
5   deltachat.node                	0x000000010e863b09 dc_event_handler + 301
6   deltachat.node                	0x000000010e890bf7 log_vprintf + 263 (dc_log.c:37)
7   deltachat.node                	0x000000010e890ab2 dc_log_info + 370
8   deltachat.node                	0x000000010e8a923c dc_sqlite3_close + 92 (dc_sqlite3.c:693)
9   deltachat.node                	0x000000010e88725c dc_close + 140 (dc_context.c:375)
10  deltachat.node                	0x000000010e88706c dc_context_unref + 76 (dc_context.c:253)
11  deltachat.node                	0x000000010e863b35 finalize_context + 23

**Pull request closed without merging**
