### PR TITLE
Catch unhandled error

### PR DESCRIPTION
**Pull request by nicodh**
Wrong credentials for IMAP causes UNHANDLED_ERROR
`{ Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Login as "uh3jbynm5f75jieu@ethereal.email" not possible. Answer imap.ethereal.email: Invalid credentials`
Happens in deltachat-desktop when updating credentials with wrong password or mailServer
see [deltachat/deltachat-desktop#695](https://github.com/deltachat/deltachat-desktop/pull/695)

### CODE REVIEW

**Comment by Jikstra** [comment]
Not sure but I think cb should get called with the error instead of just catching the error? Because with only the debug printing there's no way of knowing if the open failed or not.

**Comment by ralphtheninja** [comment]
@nicodh What is the problem here exactly? What is throwing and where is that output printed?

**Comment by nicodh** [comment]
Passing an invalid config in ipcRenderer.send('updateCredentials', config) results in:

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Login as "uh3jbynm5f75jieu@ethereal.email" failed
answer of imap.ethereal.email: Invalid credentials

    at DeltaChatController.emit (events.js:171:17)
    at onError (/deltachat/deltachat-desktop/src/main/deltachat.js:123:12)
    at DeltaChat.dc.on (/deltachat/deltachat-desktop/src/main/deltachat.js:132:7)
    at DeltaChat.emit (events.js:182:13)
    at handleEvent (/deltachat/deltachat-desktop/node_modules/deltachat-node/index.js:709:12)
    at Timeout._pollInterval.setInterval [as _onTimeout] (/o/deltachat/deltachat-desktop/node_modules/deltachat-node/index.js:573:15)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)`

**Comment by nicodh** [comment]
Ok I found now that the error can/has to be catched on a higher level. So this is obsolete...

**Pull request closed without merging**
