### PR TITLE
Make it possible to configure {imap,smtp}_certificate_checks

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Comment by link2xt** [comment]
WIP, waiting for https://github.com/deltachat/deltachat-core-rust/pull/751

**Comment by link2xt** [comment]
I have updated core in this branch.

So far my attempts to use this branch with Desktop (via `npm link`) result in segfaults. Electron starts, print the logfile name and dies with SIGSEGV. Log file is empty.

**Comment by Jikstra** [comment]
> So far my attempts to use this branch with Desktop (via npm link) result in segfaults. Electron starts, print the logfile name and dies with SIGSEGV. Log file is empty.

Ay. Currently i'm on mobile internet so can't do big pulls. I will give this a try but would refuse to merge this until that segfault is fixed. Thanks for pushing the certificate checks, i like this! I will be a bit off until the first november, hope to be able to review your prs until then but probably it won't happen before the first. @ralphtheninja maybe you can help out?

**Comment by link2xt** [comment]
@Jikstra @Simon-Laux already updated it, the question now is if it works with Desktop. Going to test later today.

**Comment by link2xt** [comment]
Rebased the PR.

Just tested it, did `git clean -xffd .`, removed all submodules etc. First built desktop repo as usual, ran it. Then did `npm link ../deltachat-node` and rebuilt it.

It works! Now I am not sure what the problem was, maybe different parts of code were compiled with different values of `DC_STR_COUNT`. Can't reproduce it anymore to run under `gdb`.

I entered my login and password, opened advanced settings, entered SMTP password again (otherwise login button does not activate, I am not sure that is correct behaviour, maybe remove this check?) and selected "strict" twice.

The result of `sqlite3 ~/.config/DeltaChat/*/db.sqlite 'select * from config where not keyname like "%_pw"'` is:
```
...
10|imap_certificate_checks|1
12|smtp_certificate_checks|1
...
23|configured_imap_certificate_checks|1
...
28|configured_smtp_certificate_checks|1
```

1 means `DC_CERTCK_STRICT`

**Pull request merged**
