### PR TITLE
[wip] Flub build

### PR DESCRIPTION
**Pull request by ralphtheninja**
Supersedes https://github.com/deltachat/deltachat-node/pull/206

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Will make a test release and try it out with desktop before merging.

**Comment by ralphtheninja** [comment]
@flub Tested it with desktop and the bindings are loaded properly etc but logging in with SMTP fails. I've tried the same user/password on current master, which works fine.

I'm wondering if this is related to libsasl somehow.

**Comment by ralphtheninja** [comment]
@flub So, I've tested some more. If I'm _inside_ the container, the integration tests work, but not if I run them outside the container. Not sure how to debug this.

If you want to try you can do:

```
$ DC_ADDR=user@site.org DC_MAIL_PW=whatever node test/integration.js
```

Replace with real account obviously. If you like I can send you some credentials so we test with the same user? (If it matters).

**Comment by flub** [comment]
it appears my merlinux test accounts no longer work :(

**Comment by flub** [comment]
when you say "outside of the container" can you give some more info?  what node version?  where is it installed?  what does `readelf -d` and `ldd` on the node binary show?  And the same on the `deltachat.node` object which you're using?

**Comment by ralphtheninja** [comment]
> when you say "outside of the container" can you give some more info? what node version? where is it installed? what does `readelf -d` and `ldd` on the node binary show? And the same on the `deltachat.node` object which you're using?

I have tried both node `v10.14.1` and the same as the one inside the container, e.g. `v11.3.0`. My node is installed using `nvm` and is under `~/.nvm/...`

```
$ readelf -d build/Release/deltachat.node

Dynamic section at offset 0x50dac8 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [deltachat.node]
 0x000000000000000c (INIT)               0xc9a20
 0x000000000000000d (FINI)               0x3f74c0
 0x0000000000000019 (INIT_ARRAY)         0x6eb540
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x6eb550
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x3a390
 0x0000000000000006 (SYMTAB)             0xd5e8
 0x000000000000000a (STRSZ)              157038 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x70f000
 0x0000000000000002 (PLTRELSZ)           109368 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xaeee8
 0x0000000000000007 (RELA)               0x64590
 0x0000000000000008 (RELASZ)             305496 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x644d0
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x608fe
 0x000000006ffffff9 (RELACOUNT)          10344
 0x0000000000000000 (NULL)               0x0
```

```
$ ldd build/Release/deltachat.node 
        linux-vdso.so.1 (0x00007ffd43790000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9b2f053000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9b2eec9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9b2ed3c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9b2ed22000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9b2eb38000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9b2f7bf000)
```

**Comment by ralphtheninja** [comment]
> what does `readelf -d` and `ldd` on the node binary show? And the same on the `deltachat.node` object which you're using?

Not sure about the distinction here. There's only one binary.

**Comment by flub** [comment]
@ralphtheninja could we work together on this sometime soon?  maybe some A/V?

**Comment by ralphtheninja** [comment]
> @ralphtheninja could we work together on this sometime soon? maybe some A/V?

Yes that's a good idea. I suppose I should rebase the branch first so it plays nice with latest master.

**Comment by flub** [comment]
On Tue 05 Feb 2019 at 07:15 -0800, Lars-Magnus Skog wrote:

>> @ralphtheninja could we work together on this sometime soon? maybe some A/V?
>
> Yes that's a good idea. I suppose I should rebase the branch first so it plays nice with latest master.

Maybe Monday after the sync?

**Comment by ralphtheninja** [comment]
@flub I've rebased the branch on latest master at least.

**Comment by ralphtheninja** [comment]
@flub Still relevant?

**Comment by flub** [comment]
I guess not if we're stopping to provide binaries here

**Pull request closed without merging**
