### PR TITLE
Remove unhelpful cargo update in rebuild-core script

### PR DESCRIPTION
**Pull request by Jikstra**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Why is this unhelpful?

**Comment by ralphtheninja** [comment]
Also, tests are failing for some reason.

**Comment by Jikstra** [comment]
> Also, tests are failing for some reason.

Rust-core broke deleting contacts, need to update it again once https://github.com/deltachat/deltachat-core-rust/pull/216 is merged

> Why is this unhelpful?

Because `cargo update` updates the dependencies in the Cargo.lock file. This is not something we want because this prevents us from locking down to a specific version of a dependency. Plus it redownloads dependencies quite often, makes rebuilding slower. We want to have more or less reproducable builds. This was mainly requested by @hpk42 :)

**Comment by ralphtheninja** [comment]
Fair enough. It's difficult to know the story behind a change when nothing is said in an issue or a PR.

**Comment by Jikstra** [comment]
> Fair enough. It's difficult to know the story behind a change when nothing is said in an issue or a PR.

Yes, sorry this happend in direct communication with hpk, could describe what's wrong with cargo update more detailed, seems like i'm a lazy human :)

**Comment by hpk42** [comment]
On Mon, Jul 22, 2019 at 15:49 -0700, Jikstra wrote:
> > Fair enough. It's difficult to know the story behind a change when nothing is said in an issue or a PR.
> 
> Yes, sorry this happend in direct communication with hpk, could describe what's wrong with cargo update more detailed, seems like i'm a lazy human :)

Cargo.lock is under version control in rust-core, it wasn't before. 
Therefore cargo-updates should be run on releases but not implicitely
in otherwise unrelated PRs etc.  Maybe it's because i am using my core-rust 
development checkout when building node and running desktop ... to be
able to more easily develop fixes for bugs i encounter during desktop/rust usage. 

and yes, jikstra: you could work a bit on your verbosity skills ;)

**Pull request merged**
