### PR TITLE
adapt to current core

### PR DESCRIPTION
**Pull request by hpk42**
this does not change naming of verified to protected to minimize changes -- this can come later.

### CODE REVIEW

**Comment by Jikstra** [comment]
Windows currently fails with ` module.obj : error LNK2019: unresolved external symbol dc_chat_is_protected referenced in function dcn_chat_is_verified [D:\a\deltachat-node\deltachat-node\build\deltachat.vcxproj]`

**Comment by Jikstra** [comment]
The problem is that the current node master still referenced deltachat-core-rust 1.46.0

**Comment by Simon-Laux** [comment]
I made a new PR which is incompatible with this one: https://github.com/deltachat/deltachat-node/pull/485

**Comment by hpk42** [comment]
well ok, then i am closing this.  i am more interesed in getting a working node-desktop-core master compatibility ...

**Pull request closed without merging**
