### PR TITLE
Update deltachat-core-rust to new (unreleased) core

### LINKED ISSUE #496: remove use of dc_contact_get_first_name
see https://github.com/deltachat/deltachat-desktop/issues/2071

### PR DESCRIPTION
**Pull request by Jikstra**
# ToDo

- [X] Remove getFirstName api closes #496
- [x] `dc_contact_get_auth_name()` https://github.com/deltachat/deltachat-desktop/issues/2109
- [X] `dc_msg_has_html()` and `dc_get_msg_html()` and `dc_set_msg_html()` https://github.com/deltachat/deltachat-desktop/issues/2078
- [x] change to contact request api
- [x] dc_contact_get_status() deltachat/deltachat-desktop#2113
- [-] ~~removal of `ImapFolder` config option?~~ not yet
- [X] chat.get_encryption_info
- [x] mailinglists
- [x] dc_msg_get_subject

Functions:
rm  dc_is_io_running ✅
add dc_get_chat_encrinfo ✅
add dc_get_msg_html✅
add dc_msg_get_real_chat_id✅
add dc_msg_get_override_sender_name✅
add dc_msg_has_html✅
add dc_decide_on_contact_request✅
add dc_msg_set_html✅
add dc_msg_set_override_sender_name✅
rm  dc_contact_get_first_name ✅
add dc_contact_get_auth_name✅
add dc_contact_get_status✅
add dc_msg_get_subject✅

### CODE REVIEW

**Comment by Simon-Laux** [comment]
why `Don't add constants where value is not a number`?
what constants are included that are not numbers?

**Comment by r10s** [comment]
> removal of ImapFolder config option?

what is that option about?

**Comment by Simon-Laux** [comment]
> what is that option about?

that's the question? its the watch folder setting afaik and the new core watches all folders if i understood it correctly, so my question is whether we need to remove the watch folder setting from desktop when using the new core.

**Comment by r10s** [comment]
> its the watch folder setting afaik and the new core watches all folders if i understood it correctly, so my question is whether we need to remove the watch folder setting from desktop when using the new core.

i see  ;) the options should stay as is for now, might be they get superfluous at some point, but we are not there yet.

**Pull request merged**
